### ISSUE TITLE
Add issue templates to the repo

### ISSUE THREAD

**Issue by MCHalbi** [MCHalbi/pollux-python#20]
**Description**
I want to have issue templates for bug reports and feature requests to have a consistent style of the 

**Definition of done**
- [x] The repository contains issue templates both for bug reports and feature requests.
- [x] The templates have a form which feels right to me.

**ToDos**
- [x] Add default GitHub templates to repository
- [x] Elaborate, which sections in the templates I do not need and remove them
- [x] Add sections I need and which are not already in the GitHub templates
