### ISSUE TITLE
Add GitHub actions

### ISSUE THREAD

**Issue by MCHalbi** [MCHalbi/pollux-python#21]
**Description**
I want to have some basic GitHub actions to be run in PRs and when code is pushed.
This should be done to avoid broken code and increase overall code readability.

**Definition of Done**
- [ ] PRs should run and enforce:
  - [ ] Codestyle check (linter)
  - [ ] Test suite
- [ ] Pushes to any branch should trigger:
  - [ ] Codestyle check (linter)
  - [ ] Test suite

**Considered Alternatives**
Since I am working alone on this project (at least right now), it is not really necessary to create a pipeline and have all the extra work to be put into it. But there are several reasons to do it anyway:
1. I want to learn how to use GitHub actions.
2. Enforcing a consistent code style is never a bad idea and I want to make it more of a habit than a burden to stick to it. 
3. There is always the possibility that other people jump on the project. It does not hurt to have a pipeline installed beforehand.

**ToDo**
- [ ] A list of action items ...
- [ ] which are required to be done ...
- [ ] to get the repo into a state ...
- [ ] where all items in the definition of done ...
- [ ] can be checked off.
