### ISSUE TITLE
Create workflow to automatically create branch for issues moved to status "Open"

### ISSUE THREAD

**Issue by MCHalbi** [MCHalbi/pollux-python#22]
**Description**
It would be convenient to automatically create a feature branch from an GitHub issue whenever it its state is changed to "In Progress". This removes two manual steps:
1. Create feature branch.
2. Link feature branch to issue.

**Definition of Done**
- [ ] A feature branch is created and linked to an Issue whenever:
  - [ ] The previous state of the issue was "Open"
  - [ ] The new state of the issue is "In Progress"
  - [ ] The Issue has no feature branch linked to it

**Considered Alternatives**
Could be done by hand, maybe it will. But for now I want to learn about GitHub workflows and this is a good opportunity to tinker around.

**ToDo**
- [ ] Create draft Workflow
- [ ] Update the workflow to do the business logic described above
